---
title: "Background and Overview"
format: html
---

The Everglades is an approximately 11,000 km2 wetland ecosystem at the southern tip of Florida, USA, and is the subject of one of the largest wetland restoration efforts in the world. Because of its subtropical position, rainfall in the Everglades is produced by highly variable annual contributions from tropical and continental weather systems, and is strongly affected by global weather patterns like ENSO and NAO. This rainfall is a critical component that supports one of the largest seasonal populations of long legged wading birds in the world (herons, egrets, ibises, storks and spoonbills, orders Ciconiiformes and Pelecaniformes). These birds nest during the dry season (November through April) when water levels recede and concentrate aquatic prey animals at shallow water depths that increase wading bird foraging success (5-25 cm depending on species, Gawlik 2002; Frederick et al. 2009).  Annual nesting population size is driven primarily by food availability (Frederick and Spalding 1994, but see Mercury effects below), and food availability is driven both by standing stocks of prey, and by the degree to which prey are concentrated by water level recession during the dry season.  Standing stocks of avian prey (small fishes and crustaceans) generally are low compared to other wetland ecosystems because of extremely low availability of phosphorus in this strongly oligotrophic system (Turner et al. 1999).  Prey population dynamics follow a parabolic response to periods of drying of surface water (Botson et al. 2016, Trexler et al. 2005, Dorn et al. 2006).  At short hydroperiods (short time interval since drying of surface waters), prey standing stocks are depressed because they are limited by water extent and frequent desiccation.  At long hydroperiods, populations of large piscine predators become established, and may limit small fish and crustacean populations via predation (Dorn et al 2006).  Hydroperiod effects are obviously dependent on antecedent water conditions, with lag times of 2 - 5 years possible. The relationship between water, aquatic prey animals, and avian breeding populations is thus largely driven by rainfall and its immediate and antecedent effects on water levels.

The Everglades hydrologic system has been strongly modified by humans beginning in the early 21st century and then accelerating in the middle of that century (Sklar et al. 2005).  These modifications included compartmentalization of water through the creation of vast impoundments, and controlled transport of water through an extensive system of dikes and canals.  Water management in this modified hydrologic system has been aimed largely at both protection of the water supply for agriculture and urban use, and buffering human populations and infrastructure from flooding.  These actions have collectively resulted in grossly reduced water flow to the coastal regions of the system, near-permanent water in impounded areas, and considerable loss of fresh water to coastal systems through canals. This has led to generally depauperate populations and availability of small fishes and crustaceans in both impounded and over drained areas (Trexler et al. 2005, Lorenz ), with consequent reductions in wading bird (Ogden 1994, Lorenz 2013) and alligator (Alligator mississippiensis, Mazzotti et al. 2009) populations, and a collapse of estuarine ecosystems historically fed by freshwater flow from the Everglades (Fourqurean and Robblee 1999).  These known effects across an immense wetland have collectively been formalized into a “Trophic Hypothesis” which posits that more historically relevant hydroperiods and spatially appropriate distribution of water will lead to restoration of fish, crustacean, alligator and bird populations, and vegetation communities. A major restoration effort has been aimed at restoring water flows and hydroperiods to the Everglades (Sklar et al. 2005), a process that may take decades and is currently ongoing.

In addition to hydrological modifications, mercury (Hg) from atmospheric and local sources has become a major pollutant during the last half century in the Everglades (Frederick 2000).  Hg has outsized effects in this ecosystem both because Hg is highly biomagnified by long aquatic food webs, and because chemical and hydrobiotic conditions in this wetland are excellent for transforming Hg into its most toxic methylated form (Gilmour et al. 1998). Hg is known to have strong effects on neurological, endocrine, and reproductive systems in birds generally (Whitney and Cristol 2018), and in this system may account for up to 50% reductions in productivity.  Because of shifting water levels, input sources, and methylation conditions, Hg may vary in its availability by three orders of magnitude across locations and time in the Everglades (Frederick et al. 2005).  In wading bird populations, Hg interacts strongly with food availability in determining both propensity to breed in any year, and success of nesting (Zabala et al. 2022). While these effects are relatively well known for birds, there may be similarly depressive effects of Hg on fishes, alligators and other animal populations (Wolfe et al. 1998, Frederick 2000).  The Everglades is also now home to numerous invasive species, which may affect both predation on nesting birds (Orzechowski et al. 2019), and a gross reduction in aquatic prey animal populations (Pintar et al. 2023).  In addition, the entire ecosystem is extremely low lying and quite susceptible to rising sea level (Titus and Richman 2001), and climate change effects on rainfall patterns could strongly affect hydrological responses (Nungesser et al. 2015).

Because of the naturally hypervariable nature of the Everglades, and because the suite of novel anthropogenic effects are constantly changing, a long term monitoring approach seems the only way to understand whether restoration is working. Fortunately the Everglades has a rich and long history of monitoring of wading birds, extending over a century for some indices (Frederick and Ogden 2003).  Annual surveys of some colonies were begun in the 1930s, and consistent monitoring of breeding and foraging by wading birds began in  the 1980s.  Here, we describe in detail the ecosystem-wide monitoring system that has been developed during the last thirty years, both to codify a reproducible monitoring system, and to serve as a heuristic or specific model for other ecosystems.
