---
title: "Methods"
format: html
---

## Nest Surveys

Since 1993, we have monitored nest success (probability of any nest producing one or more chicks) for White Ibis, Great Egrets, Wood Storks, Roseate Spoonbills, Snowy Egrets, Tricolored Herons, Little Blue Herons, Black Crowned Night Herons, Great Blue herons, and Glossy Ibis. Not all species nested every year and not all actively nesting species were nesting within monitored colonies. Therefore, nest success data for each species may not be consistent. This monitoring was conducted on foot by field crews that visited active colonies once every 5-7 days. Each year, nest success transects were typically established in 4-7 colonies, though depending on conditions and funding sometimes fewer colonies are monitored. Colonies were selected that were likely to have accessibility throughout the season, were large size in size and represented variable species composition, had historic nest success data, and contained Everglades restoration target species which included Great Egrets, Snowy Egrets, Wood Storks, White Ibis, and (later) Roseate Spoonbills. While consistent colony monitoring was desired between years, colonies can be occupied by variable species, and not all colony locations are active every year (Frederick and Spalding 1994). Transects were established once an estimated 80% of all nests in the colony had eggs present since disturbing a colony before incubation risks colony abandonment. Colony status was determined via air surveys and quick on-the-ground visits, with field crew looking for behavior cues (courting, pairing, and sitting on nests) and nests containing eggs. Once safe to enter, a trail was marked with surveyor flagging and all active wading bird nests within 10 meters of the trail were marked with individually numbered flagging, identified to species based on construction materials, size, shape, location, and egg and chick characteristics (McVaugh 1972). Because the field crew can only remain in the colony for 1 hour to minimize impacts on nesting success, transect length can vary across years and colonies depending on nest density and travel conditions within the colony. For the safety of birds and people, nest checks may be halted or postponed for adverse weather conditions, predator presence, or signs of extreme stress in birds. The field crew visited each transect/colony approximately weekly. Nest contents were observed using extendable mirror poles and recorded in a write-in-the-rain notebook. Primary data included number of eggs and number of chicks for each marked nest. Detailed notes were also taken of egg/chick conditions, or any other useful observations (e.g., pipping eggs, cold or broken eggs, dead chicks) which could help determine nest age and/or fate. If new nests appeared on the transect as the breeding season progressed these were also flagged and followed until nest fate was known. Nests were assumed to have failed when all eggs or chicks disappeared or were found dead prior to the fledging age. Colonies were monitored from the time most nests had progressed to incubation until all nests on the transects had either failed, produced young to 14 days of age (White Ibis, Snowy Egret, Tricolored Heron, Little Blue Heron, Glossy Ibis), 21 days of age (Great Egret, Roseate Spoonbill, Black Crowned night heron) or 50 days (Wood Stork), or were no longer accessible to airboats. To minimize the stress of human intrusion on breeding colonies, all work within active nesting colonies was usually completed by 7 to 10 am when temperatures are moderate (around 75-80 °F), to minimize heat stress on eggs and young. If birds showed signs of stress during any visit, the field crew would leave the colony before all nests were checked and may have chosen not to return for subsequent visits, depending on field crew assessment. If other known researchers were entering colonies, the field manager coordinated visits to minimize colony disturbance. While the core data collection method has been consistent, some changes in species focus and access have occurred over time. Initially, species of interest included Great Egrets, White Ibis, and Snowy Egrets. Visits to Wood Stork colonies did not occur in the earlier years because Wood Storks did not nest in the Water Conservation areas. Wood Stork colonies were monitored in Everglades National Park from monthly aerial surveys and status was determined by how many nests contained chicks close to the fledge date. After 1999, Wood Storks began nesting at the edge of WCA 3 in Tamiami West colony and weekly nest checks began at this time. Roseate Spoonbills began to move from nesting colonies in Florida Bay to colonies in the WCA's in the early 2000's. Black Crowned Night Herons also began nesting in colonies in the early 2000's and were subsequently included when they were present on the transects. Anhinga nests were actively avoided because chicks jump out of the nest when feeling threatened.

## Nest Stage

During surveys, date, colony, species, number of eggs, and number of chicks are recorded. The nest is also assigned a 'stage' based on it's overall condition.

| Nest Stage                                              |                                                                                                                                                                                        Description                                                                                                                                                                                         |
|:-----------------------|:----------------------------------------------:|
| incubating ^6^                                          |                                                                                                                                     All eggs, nothing of note happening, this should be used the vast majority of the time there are eggs in the nest.                                                                                                                                     |
| pipping ^3^                                             |                                                                                                                                          Important aid to determine hatch date of first chick (usually hatch 24 hours after pipping observation)                                                                                                                                           |
| hatching ^2^                                            |                                                                       Eggs AND chicks in the nest at the same time (it is NOT hatch date). Should only be used on 1 visit. Trumps chick_dry unless you don't think more eggs will hatch. Assume any eggs left in nest are dead after a week, and just use nestling.                                                                        |
| wet_chick ^1^                                           |                                                                                                                                             More indicative of hatch date than pipping, outweighs hatching or pipping of second or third eggs                                                                                                                                              |
| nestling ^7^                                            |                                                                                                                                   All chicks, nothing of note happening, this should be used the vast majority of the time there are chicks in the nest.                                                                                                                                   |
| branchling ^5^                                          |                                                                                       Nest is empty but pre-fledged chicks observed in canopy above nest, usually when chicks are about to fledge and only a minimum number of chicks are observed. Plumage and size indicate they will soon fledge.                                                                                       |
| empty ^8^                                               |                                                                                                                                                          No live eggs or chicks in nest. Most likely written in the book as "MT"                                                                                                                                                           |
| missed ^14^                                             |                                                                                                                                                                     Nest was not checked, fate not known for that date                                                                                                                                                                     |
| Assigned only by field manager and/or at end of season: |                                                                                                                                                                                                                                                                                                                                                                                            |
| re_lay ^9^                                              |                                                                                                                                       Eggs present in nest that was previously empty, start again with new number on new row, and this stage value.                                                                                                                                        |
| chick_dry ^4^                                           |                                    Youngest chick in nest is dry (suggests hatched previous day at the latest), indicates no more hatching will happen (eggs left or not). Should only be used on 1 visit, if at all, and only if you have previous egg observations. Otherwise see aged_chick, or just use nestling if the data likely cannot be used.                                    |
| fledged ^10^                                            |                                                                                                                                 Chicks definitely fledged. eg: chicks run or fly out of nest. Behavior observation, not based on age or size, subjective.                                                                                                                                  |
| collapsed ^13^                                          |                                                                                                                 Useful information for field activities, but not nest success. "Empty" outweighs collapsed nest, flagging sometimes pulled, typically used in field notes.                                                                                                                 |
| failed ^12^                                             |                                                                                                                                      Don't assume, better to leave nest categorized as "empty" unless purely obvious (chicks may have run off, etc.).                                                                                                                                      |
| aged_chick ^11^                                         | This is to be used only when the time between nest checks exceeds the usual 7 days, such as having to skip a week due to WHIB courtship. No observations of eggs in nest. This should be the first nest stage assigned and only used once. Only to be used when the youngest chick can be aged as \<5-7 days with some confidence. Meaning: don't throw out these data, keep for Mayfield. |
| unknown ^15^                                            |                                                                                                                Used when the fate of a nest cannot be determined and needs to be excluded from Mayfield calculations, but still has useful information, such as incubation.                                                                                                                |

Table Notes:

"Pipping," "wet_chick," and "chick_dry" always refer to youngest egg or chick.

Superscripts indicate the hierarchy to be used when deciding between stages.
