---
title: "Find Nests"
author: "Ben Weinstein"
date: "6/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Aim

The goal of this document is to read predictions ffrom the deep learning detection model and assess the number of bird detections per site and overtime. By comparing the location of detected birds among flights, we can assess potential nest success and create data for a meta-population model.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
library(sf)
source("nesting_functions.R")
```

```{r}
PATH_TO_DATA = "/Users/Ben/Dropbox/Everglades/predictions/20200629_171635/"
files<-list.files(PATH_TO_DATA,full.names=T,pattern=".shp")
shapefiles<-lapply(files,function(x){
  df<-read_sf(x)
  df$site <- get_site(x)
  df$event <-  get_event(x)
  return(df)
  })
df<-do.call(rbind,shapefiles)
df$label<-"Bird"
head(df)

#layer filter
df<-df %>% filter(score>0.3)
```

Write a copy to the shiny app
```{r}
#Write centroids 
df_centroid<-st_centroid(df) %>% select(-xmin,-xmax,-ymin,-ymax)
st_write(df_centroid,"../App/Zooniverse/data/PredictedBirds.shp",delete_layer=T)
```

