name: Zooniverse
channels: 
  - defaults
dependencies:
  - python==3.7
  - geopandas
  - shapely
  - pandas
  - pytest
  - pip
  - dask
  - distributed
  - pip:
    - panoptescli
    - mapboxcli
    - rasterio
    - deepforest
    - comet_ml
    - paramiko
    - opencv-python



