---
title: "Methods"
format: html
---

Systematic ground surveys of colonies by airboat are designed to locate and document small colonies or those of dark-colored species that are difficult to detect from aerial surveys, primarily little blue herons and tri-colored herons. Since 1996, systematic ground surveys of colonies have been conducted by airboat when small herons are at peak incubation, which is usually late March through early May. While originally covering all of WCAs 1,2, and 3, they were reduced to a subsection of WCA3 in 2005. Because current ground surveys are a subset of pre-2005 surveys, they allow for a direct comparison of densities of colonies in that area.

Surveys consist of 16 500m-wide North-South oriented transects in WCA 3A that are spaced 500 m apart. This covers an area that extends from US-41 (Tamiami Trail) to I-75 (Alligator Alley), and from the L-67 canal westward to the border of Big Cypress National Preserve. The four western-most transects (13 through 16) do not fully extend to I-75 but instead end at the southern border of the Miccosukee reservation. Surveys initially extended into the Miccosukee reservation but since 2014 transects end at the signs for the reservation boundary.  A two-person team, composed of an airboat operator and a primary observer, usually complete two transects each day of the survey. Beginning from the south, the first transect is conducted traveling  north and the adjacent transect completed while traveling south. 

All tree islands are approached close enough to flush potential birds. If wading birds or Anhingas are present, the tree island location is recorded via GPS at the north end of the island. A new point is logged regardless of whether the island has been recorded in previous years. Flushing birds are counted by both persons. Nests and nestlings are counted as well if observable, or later estimated from flushed birds. Counts of nests in a few small colonies indicated a close correspondence between the number of birds flushed and the number of nests found in the colony (L. Garner, pers. comm)  - though this does not apply to black-crowned night herons which often use small tree islands as daytime roosts (Maccarone and Hamilton 2014). Because birds in the interior of larger colonies are less likely to flush when approached by an airboat and large numbers are more difficult to count accurately, this approach is best used with smaller colonies. Large colonies on these transects are few in number.

While the goal is to complete the full length of each transect, year-to-year variability in water levels do not always allow for this. It is not uncommon for some fraction of the northern end of the transects to become prohibitively dry to airboat travel. This occurs more frequently in the centrally located transects, as the western-most transects end at the Miccosukee border and water dry downs usually begin in the north west and move south east. The eastern transects tend to maintain relatively higher water levels through the season.
