---
title: "Mercury - Methods"
format: html
---

Because methylmercury within the body is shed into keratinous tissue, bird feathers provide an accurate record of the mercury circulating within an individual at the time the feathers were grown (Zabala et al. 2019). Feathers are sampled from chicks because the age of the feathers are known and chicks are good bioaccumulators due to their rapid growth rates and higher demands of food relative to their body weight. Feather sampling is also less invasive than other methods and easier to conduct quickly and safely in the field. Since chicks are fed from the areas around the colony, they are excellent bioindicators of mercury in prey items in the surrounding marsh during that breeding season.

Long-term monitoring of mercury levels in wading birds has been conducted since 1994 by annually sampling feathers from Great Egret Chicks. Great Egrets feed almost exclusively on fish, are relatively high in the Everglades trophic web, and nest reliably from year to year throughout the study area. Typically, there are large differences in contamination between colonies in different parts of the Everglades due to variation in soil and water chemistry. Therefore, a high quality and consistent geographic representation throughout the area can be provided by the normal wide-spread nesting tendencies of Great Egrets as compared to other species. Samples are collected from 5-10 colonies, with priority given to colonies that have been historically and regularly sampled. These colonies include Alley North, Horus, Vacation, Hidden, Tamiami West, Mud Canal, 3B mud canal, 6th Bridge, Joule, and Jerrod. Usually, one or more of these colonies are not active or accessible in any year, so other colonies may be substituted with geographic representation in mind.

From each colony, feathers from 10 chicks are collected. Priority is given to nests that are marked, where chick age and fate are known but sometimes chicks from unmarked nests may be included to reach the desired sample size. Nests in colonies where nest monitoring is not occurring may also be sampled to obtain geographic variability and consistency across years. Chicks are sampled when they are at least 21 days of age, but usually older (28-35 days). The chicks should be large enough to run away but not large enough to evade capture via flight. Feathers should be well developed to obtain enough material, and so chicks selected should have very little down. The oldest (largest) chick in the nest is captured if possible, and ten feathers from between the scapular region (base of the cervical vertebrae) are collected. Collected feathers should be fully intact and about 1-2 inches long. Some biometrics of the chick are recorded including body weight, length of tarsus, and length of culmen (tip of bill to beginning of skin on dorsal surface of bill). Other data such as colony name, nest number, chick order (oldest, not known, etc.), and date of collection are recorded. Once sampling and measurements are complete, the chick is safely placed back in or near the nest. After 2019, additional samples were opportunistically collected from fresh, dead Great Egret chicks that were encountered during sampling. Morphometric data may not be complete for these samples if the conditions of the carcass were not conducive to data collection.

Samples are stored in labeled paper envelopes until processing. Feather samples collected prior to 2014 were sent out to a third party for processing. The amount of methylmercury levels from each sample were reported back to the lab. Samples collected after 2014 were processed in house using a direct mercury analyzer (DMA 80) and quality-controlled using known concentrations in standards.

Other periods of intensive sampling of mercury have occurred to answer other scientific questions. From 2015-2017, blood, feather, and albumin samples were collected from Great Egret chicks (Zabala et al 2019). Nests in 9-10 colonies in WCA 3 and Everglades National Park were marked and monitored for nest success throughout the breeding seasons. An albumin sample was collected from the second oldest egg from each nest 2 days after laying. Blood was collected from the hatched chick at 14 days of age, and then feathers were sampled after 21 days of age. In 2018, all chicks (sibling nestlings) (Zabala et al 2019b) in each nest were sampled via collected feathers to determine variation between chicks. 2018 was exceptionally high nesting effort and nesting success, so a large sample size was easily collected.

Short-term sampling of Wood Stork chick feathers occurred in the years XXXX through XXXX and are included in the data set.
