---
title: "Data Processing"
format: html
---
## Maximum Counts

Maximum counts (max count) are the peak number of nests observed during a single survey (either a monthly aerial survey or the ground survey) during the breeding season. Max counts are not the same as the total number of wading birds that nested in the everglades because colony abandonment can cause birds to start nests in one colony early in the season but in a different colony later in the season. Max count is also not the total nest starts over the breeding season because individuals may experience nest failure and re-nest within the same colony in a different month than the month with the most nests. Aerial transects are a critical data source for max count, but max count for smaller colonies, especially small heron colonies, comes from the ground transects conducted by airboat. Since these colonies are only surveyed once during the breeding season, ground count data are by definition the maximum number of nests observed. Aerial estimates conducted by SFWMD are also used to determine the maximum counts for colonies. The final maximum count for each species, colony, and breeding season are stored in or max_counts.csv maxcounts_under40.csv. 

### Generating Max Counts
To determine the max count of nests for each species in each colony, data and notes collected from aerial survey observer counts, aerial survey imagery counts, ground survey counts, ground-level field observations, and information from other sources such as SFWMD helicopter surveys, are combined into one source. This produces multiple nest counts for active colonies each month.  Only nesting bird counts are included when determining max counts, with some exceptions. Infrequently, we include counts of paired roosting Wood Storks who may have abandoned after the start of incubation, but before the next monthly flight due to weather conditions. Courting White Ibis counts may also be included if conditions for nest initiation were highly favorable at the time of observation, but signs of abandonment during the next aerial survey were evident. For these instances, the total number of courting or paired Wood Storks or White Ibis are divided in half and added to the month’s total. 

Once data from all sources is compiled, these data are reviewed along with any associated notes for each colony and the highest and most accurate count is selected as the max count. Image counts are generally considered the most accurate, with data from more experienced counters prioritized when there are disagreements. If image quality is poor, however, aerial observer counts or SFWMD counts are preferred. Notes from aerial observations, field observations, and overall nesting conditions are also reviewed and considered when deciding which counts are most accurate. These observational notes are used to aid in identifying nest stage and species present. For example, if the number of Great Egret nests suddenly increases in May, a review of the counts may show that fledged chicks were erroneously counted as nests. This is further validated by recorded ground observations of large fledged chicks and the conclusion of Great Egret nesting in that area. Max counts for every species at every colony surveyed are determined, except for Green Herons which are not colonial nesters. Observations and counts by SFWMD biologists are especially useful to determine the ratio of species in mixed colonies that are hard to discern, such as Little Blue Heron, Snowy Egret, and White Ibis. Additionally, SFWMD conducts surveys at various times and may capture nesting events between our monthly aerial surveys.  

In mixed colonies with species that are hard to discern, such as Snowy Egret, Little Blue Heron, and Tricolored Heron, observers will often record a collective number of "Small White" birds. The ability to identify these birds to species from the air can depend on the conditions and on the behavior of the birds. Thus, species-level identification may be possible one month, during courtship behavior, but not possible the next month when birds are sitting on nests. Max counts at the species level are preserved by maintaining any and all species-level counts recorded. These are then used to adjust the total number of "small whites" recorded. 

Examples: 
* There are 40 SNEG and 180 SMWH in March, and 200 SMWH in April. We would report March's numbers as that is more collective SMWH nests.

* There are 20 SNEG counted in March, then 60 SMWH in April. We would subtract the 20 SNEG from the 60 SMWH, and report it as 20 SNEG and 40 SMWH in order to preserve species info.

Most colonies surveyed by ground transects are missed on aerial surveys because they are small with few easy-to-spot species. Any colony where easy-to-spot species (Great Egret, Wood Stork, White Ibis, Snowy Egret, Roseate Spoonbill) were seen during ground surveys is cross-checked against aerial surveys to ensure the colony is not entered twice for max counts (ground count colony ID is different from aerial survey colony ID). The max count of each species either ground surveys or aerial surveys, is selected for these locations. This eliminates double counts of colonies counted via both survey methods. 
Max counts for a colony are added to either maxcounts_under40.csv (for colonies that have never had more than 40 pairs of breeding birds) or max_counts.csv (for colonies that have reached >40 pairs of breeding birds at least once during the history of the study). In past years, there may be locations listed on the max count table with zero counts. These instances are most likely where non-target species were present such as Green Herons, Anhingas, or Cormorants, or where nests were observed with chicks, but no adult (GBHE typically).
The weighting of data sources for max counts has changed over time. Initially, aerial observer counts and ground counts were prioritized. However, as camera technology and improvements in image quality increased, and usability became more feasible, photo based counts have become the more accurate and therefore preferred method. 

