---
title: "Data Processing"
format: html
---

### Aerial Image Processing

Because counting photos is labor intensive, photos are taken every month of every active colony but not all photos are automatically counted. If it is obvious that certain months of an active colony are the max nesting months, then other months may not be counted. For example, later months such as May and June are usually not counted for Great Egrets, Wood Storks, or Roseate Spoonbills, as they have usually fledged or failed nests by this time. However, small heron or White Ibis colonies may be reviewed and counted as they frequently nest later or are more asynchronous. 

After each aerial survey, photos are loaded onto two separate hard drives for storage and backup. Files are organized by year, month, and colony. Photos for each colony consist of a zoomed out photo, for orientation, and multiple zoomed-in photos. All photos of a colony are reviewed to select the highest quality images. Most colonies can be counted using just one to three images, but larger islands and groups of islands may require manually stitching a subset of photos to count the entire colony. We count the target species (Great Egret, White Ibis, Snowy Egret, Wood Stork, and Roseate Spoonbill) and Great Blue Herons (due to their visibility). Because some species (White Ibis, Snowy Egrets, and white chicks in Little Blue Heron) are difficult to discern in mixed colonies due to the often low visibility of subcanopy nests, there is also an “Unknown Small White” category for counting. Dark species are also counted when seen, but should only be considered as a minimum count due to their low detection rates. As camera technology improves, some small dark species, such as Little Blue Herons, have become easier to identify and count in certain vegetation communities. Their presence is also noted if observed. It is not clear if there is a solution to distinguish Snowy Egrets and White Ibis counts from each other in large mixed colonies due to their similar nesting phenology and the full/partial occlusion of nests due to canopy cover (Williams et al). 

Before digital photos, slides of colony imagery were projected onto a screen and counted with the aid of hand clickers. Digital photos were initially processed similarly, except photos were displayed on computer monitors using Microsoft Paint and counted with the aid of a hand clicker. With the adoption of Adobe Photoshop, the count tool is used to label (by species and behavior) and count individual nests. This results in a photo with counted and labeled nesting and roosting birds. This tool also allows users and reviewers to easily visualize what has been counted as each label can be color coded. The user is counting nests, not birds, but an incubating or brooding bird equates to one nest. In addition to nests, roosting or courting birds are counted, and sometimes other behaviors or fledged chicks may also be categorized and counted. The counted photos are saved in the corresponding colony folder and labeled with the name of the counter. 
All photos are reviewed by the project coordinator who was also the primary observer and photographer in every flight. Adjustments or recounts usually occur due to incorrect species ID, or incorrect behavior (labelled as nesting when birds were only standing on empty nest platforms)
