# Install packages, update data, test, and archive 

name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 11 * * 2"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  build:
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - uses: r-lib/actions/setup-r@master
      
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          
      - name: Install system dependencies
        run: |
          sudo apt-get install libgit2-dev

      - name: Install packages
        run: Rscript install-packages.R

      - name: Update data
        run: Rscript update-data.R
        
      - name: Test
        run: Rscript testthat.R
        
      - name: Archive
        run: Rscript archive.R
